import Poolot from '../src/assets/Images/poolot1.png';
import Vernchain from "../src/assets/Images/vernchain01.png";
import Login from "../src/assets/Images/Login.png";
export const projects =[
    {
        id: 1,
        imageUrl:Poolot,
        status:'Featured',
        statusName:'Poolot',
        name:'Poolot Landing Page',
        description:'Built a website where users can easily sign up, log in, and securely access their account. It welcomes them by name and allows them to log out anytime',
        skills:[
            'React Js',
            "Tailwind Css",
            'Framer Motion',
        ],
        github:'https://github.com/Nixxy25/personal-project',
        website:'https://poolot-landingpage-omega-lovat.vercel.app/',
    },
    {
        id: 2,
        imageUrl:Vernchain,
        status:'Featured',
        statusName:'VernChain',
        name:'Vernchain Landing Page',
        description:'Built a website where users can easily sign up, log in, and securely access their account. It welcomes them by name and allows them to log out anytime',
        skills:[
            'React Js',
            "Tailwind Css",
            'Framer Motion',
        ],
        github:'https://github.com/Nixxy25/VernChain-Website',
        website:'https://vermchain-eight.vercel.app',
    },
    {
        id: 3,
        imageUrl:Login,
        status:'Featured',
        statusName:'Login',
        name:'Login Landing Page',
        description:'Built a website where users can easily sign up, log in, and securely access their account. It welcomes them by name and allows them to log out anytime',
        skills:[
            'React Js',
            "Tailwind Css",
            'Framer Motion',
        ],
        github:'https://github.com/Nixxy25/OIBSIP-LOGIN-AUTHENTICATION',
        website:'https://poolot-landingpage-omega-lovat.vercel.app/',
    },
    {
        id: 4,
        imageUrl:Poolot,
        status:'Featured',
        statusName:'Poolot',
        name:'Poolot Landing Page',
        description:'Built a website where users can easily sign up, log in, and securely access their account. It welcomes them by name and allows them to log out anytime',
        skills:[
            'React Js',
            "Tailwind Css",
            'Framer Motion',
        ],
        github:'https://github.com/Nixxy25/personal-project',
        website:'https://poolot-landingpage-omega-lovat.vercel.app/',
    },
    {
        id: 5,
        imageUrl:Poolot,
        status:'Featured',
        statusName:'Poolot',
        name:'Poolot Landing Page',
        description:'Built a website where users can easily sign up, log in, and securely access their account. It welcomes them by name and allows them to log out anytime',
        skills:[
            'React Js',
            "Tailwind Css",
            'Framer Motion',
        ],
        github:'https://github.com/Nixxy25/personal-project',
        website:'https://poolot-landingpage-omega-lovat.vercel.app/',
    },
]